modLoader="javafml"
loaderVersion="[40,)"
license="Apache 2.0"

[[mods]]
modId="paimonfood"
version="${file.jarVersion}"
displayName="PaiMonFood"
displayURL="https://github.com/Dabai1025/PaimonFood"
authors="LDS_DB"
description=''''''

[[dependencies.paimonfood]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.paimonfood]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
